import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Main from "./components/main";
import Discusion from "./components/dicusion";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: "white" }}>
        <Header />
        <Main/>
        <Discusion/>
        {children}
      </body>
    </html>
  );
}
