import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Main from "./components/main";
import Discusion from "./components/dicusion";
import About from "./components/about";
import Services from "./components/services";
import Team from "./components/team";
import Power from "./components/power";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: "white", }}>
        <div className="container">
          <Header />
          <Main />
          <Discusion />
          <About />
          <Services />
          <Team />
          <Power/>
        </div>
        {children}
      </body>
    </html>
  );
}
